apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: AnilA
  namespace: argocd
spec:
  destination:
    namespace: anilA
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: argo
    repoURL: "https://github.com/mkum0001/Mittana-devops-youtube-series"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
