apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: anilA
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argo
    repoURL: "https://github.com/mkum0001/Mittana-devops-youtube-series"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
